# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/api
Content-Type: application/json

{"firstName":"A8","lastName":"B8","email":"a8@b.com"}

###

PUT http://localhost:8080/api
Content-Type: application/json

{
  "id": 10,
  "firstName":"A10",
  "lastName":"B10",
  "email":"a10@b.com"
}

###

POST http://localhost:8080/api/10
Content-Type: application/json

{
  "date": "2019-01-31",
  "grade": 7
}

###

DELETE http://localhost:8080/api/10

###